spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/springcloud_sell_joy/config-repo
          username: isongliang@qq.com
          password: songliang123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
